const fs = require('fs');
const path = require('path');
const outDir = 'C:/Users/User/Projects/leap-edge-website';
const t = fs.readFileSync(path.join(outDir, 'unpacked-template.html'), 'utf8');
const dcStart = t.indexOf('<x-dc>');
const dcEnd = t.indexOf('</x-dc>') + 7;
const xdc = t.slice(dcStart, dcEnd);
const scriptTagStart = t.indexOf('data-dc-script');
const gt = t.indexOf('>', scriptTagStart) + 1;
const scriptEnd = t.indexOf('</script>', gt);
const componentScript = t.slice(gt, scriptEnd);
const propsStart = t.indexOf('data-props="', scriptTagStart) + 'data-props="'.length;
const propsEnd = t.indexOf('">', propsStart);
const propsRaw = t.slice(propsStart, propsEnd).replace(/&quot;/g, '"').replace(/&amp;/g, '&');
fs.writeFileSync(path.join(outDir, 'xdc-template.html'), xdc);
fs.writeFileSync(path.join(outDir, 'component-source.js'), componentScript);
fs.writeFileSync(path.join(outDir, 'props.json'), propsRaw);
console.log('xdc:', xdc.length);
console.log('script:', componentScript.length);
console.log('script preview:\n', componentScript.slice(0, 2000));